### ISSUE TITLE
Prerelease issues

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#109]
When testing just now I've noticed the following things:

## Viewer

- [x] The Dir library table for metagenome-hostassociated seems to hjave `sample_host` column right at the end when you download it?
- [x] Why is the nf-core/mag csv saved as a ZIP file?
- [ ] Would it make sense to have `run_accesion` as the ERR code in the nf-core/taxprofiler output?
- [x] ~~Why is aMeta only containing the R1/forward read (one for @NikolayOskolkov )~~ Edit: aMeta only accepts single-end or already merged reads. I will document
- [x] The nf-core/fetchngs accession sheet seems to have additional columns (possibly of fAstq size? I'm not sure...)

## Convert

- [x] All `convert` commands get a `TypeError: run_convert() got an unexpected keyword argument 'library_output'` error

    ```
    (amdirt) james@bionb103:/tmp$ AMDirT convert ancientmetagenome-hostassociated_samples.tsv ancientmetagenome-hostassociated_sample -o .
  2023-04-18 13:11:50.843 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.845 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.846 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.846 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.846 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.847 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.848 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  2023-04-18 13:11:50.848 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
  Traceback (most recent call last):
    File "/home/james/bin/miniconda3/envs/amdirt/bin/AMDirT", line 33, in <module>
      sys.exit(load_entry_point('AMDirT', 'console_scripts', 'AMDirT')())
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/home/james/git/spaam-community/AMDirT/AMDirT/cli.py", line 154, in convert
      run_convert(**kwargs, **ctx.obj)
  TypeError: run_convert() got an unexpected keyword argument 'library_output'

    ```
- [x] Convert is missing the AncientMEtagenomeDir Liobraries, citations  and download script options
- [x] convert prints streamlit info even though streamlit isn't involved (presumably)

    ```
    2023-04-19 08:59:01.113 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.115 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.115 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.116 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.116 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.117 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.117 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.118 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
    AMDirT [INFO]: Preparing nf-core/eager table
    2023-04-19 08:59:01.612 
      Warning: to view this Streamlit app on a browser, run it with the following
      command:
    
        streamlit run /home/james/bin/miniconda3/envs/amdirt/bin/AMDirT [ARGUMENTS]
    2023-04-19 08:59:01.612 No runtime found, using MemoryCacheStorageManager
    2023-04-19 08:59:01.622 No runtime found, using MemoryCacheStorageManager
    AMDirT [INFO]: Preparing Bibtex citation file
    2023-04-19 08:59:01.639 No runtime found, using MemoryCacheStorageManager
    AMDirT [INFO]: Writing filtered libraries table
    Traceback (most recent call last):
      File "/home/james/bin/miniconda3/envs/amdirt/bin/AMDirT", line 33, in <module>
        sys.exit(load_entry_point('AMDirT', 'console_scripts', 'AMDirT')())
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "/home/james/bin/miniconda3/envs/amdirt/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/james/git/spaam-community/AMDirT/AMDirT/cli.py", line 154, in convert
        run_convert(**kwargs, **ctx.obj)
      File "/home/james/git/spaam-community/AMDirT/AMDirT/convert/__init__.py", line 132, in run_convert
        fw.write(accession_table["curl_script"])
    UnboundLocalError: local variable 'accession_table' referenced before assignment
    ```

**Comment by maxibor** [comment]
>  All convert commands get a TypeError: run_convert() got an unexpected keyword argument 'library_output' error
Fixed with b45211fcd842fd69a8e4a364cf2fc5766634639c

**Comment by maxibor** [comment]
>  Convert is missing the AncientMEtagenomeDir Liobraries, citations and download script options
It already has them, they're just generated by default, hence not in the CLI options

libraries table: https://github.com/SPAAM-community/AMDirT/blob/ddb3fd31dd945cdd49170f7ac2b9c56a7448ad03/AMDirT/convert/__init__.py#L122

bibtex: https://github.com/SPAAM-community/AMDirT/blob/ddb3fd31dd945cdd49170f7ac2b9c56a7448ad03/AMDirT/convert/__init__.py#L118

**Comment by maxibor** [comment]
> Why is the nf-core/mag csv saved as a ZIP file?

Because it has two files, once for PE libraries, and one for SE libraries

**Comment by jfy133** [comment]
INote I've fixed the `UnboundLocalError: local variable 'accession_table' referenced before assignment` error in convert #113 , but streamlit stuff still applies
