### ISSUE TITLE
Data structure change breaks DOI checking

### ISSUE THREAD

**Issue by jfy133** [SPAAM-community/AMDirT#59]
To clarify when paper (e.g. reporting a microbial genome) that re-used public data, we have renamed in the library table `publication_doi` to `data_publication_doi`. However this breaks the current duplicate DOI checking:

https://github.com/SPAAM-community/AMDirT/blob/e5bcc4a601f8ae16bfb739d70e45fedfa99b1ae6/AMDirT/test_dataset/main.py#L205-L206

We should consider a way to loosen the expected 'hardcoded' column names.

**Comment by jfy133** [comment]
However it could theoretically be that people re-use public data in multiple publications :thinking: so maybe we just need to drop this for the library level metadata.

**Comment by jfy133** [comment]
Another one is `archive_run_accession` -> `archive_data_accession` but I should be able to fix that myself :eyes: (Or I will try to)

**Comment by maxibor** [comment]
This has been made more flexible with the rewrite. But that will require a manual verification when this happens again.

**Comment by jfy133** [comment]
I'm assigning myself to test this during the hackathon

**Comment by maxibor** [comment]
Adressed in #69

**Comment by jfy133** [comment]
Not sure if that is related but when adding `-i` and checking the library tables I get the following error

```
AMDirT validate ancientmetagenome-hostassociated_libraries.tsv ancientmetagenome-hostassociated_libraries_schema.json -v -d -c -i
Traceback (most recent call last):
  File "/home/jfellows/.conda/envs/amdirt/bin/AMDirT", line 33, in <module>
    sys.exit(load_entry_point('AMDirT', 'console_scripts', 'AMDirT')())
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jfellows/Documents/git/spaam-community/AMDirT/AMDirT/cli.py", line 66, in validate
    run_validation(**kwargs, **ctx.obj)
  File "/home/jfellows/Documents/git/spaam-community/AMDirT/AMDirT/validate/__init__.py", line 27, in run_validation
    v.check_duplicate_dois()
  File "/home/jfellows/Documents/git/spaam-community/AMDirT/AMDirT/validate/application/__init__.py", line 9, in check_duplicate_dois
    project_dois = self.dataset.groupby("project_name")["publication_doi"].unique()
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 1338, in __getitem__
    return super().__getitem__(key)
  File "/home/jfellows/.conda/envs/amdirt/lib/python3.10/site-packages/pandas/core/base.py", line 250, in __getitem__
    raise KeyError(f"Column not found: {key}")
KeyError: 'Column not found: publication_doi'

```

**Comment by jfy133** [comment]
Note that `publicadion_doi` is now `data_publication_doi` in teh librar ymetadata table as described above

**Comment by maxibor** [comment]
@jfy133 should also now be fixed
